spring.application.name=AICAttendanceSystem

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/aicattendancedb
spring.datasource.username=postgres
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
